### ISSUE TITLE
Parse panics on input without double quotes

### ISSUE THREAD

**Issue by dmitshur** [peterhellberg/link#6]
(Reporting in case it is helpful.)

The following input causes `Parse` to panic:

```Go
link.Parse(`</example.png>;rel=preload;as=image`)
```

(Playground link: https://go.dev/play/p/yZcgx_-7G_4.)

The input comes from the real world and may or may not be valid. (From a quick look over RFC 5988, it seems that it might be okay.)

The panic can be minified to `link.Parse("</example.png>; rel=preload")`. It seems it happens when there aren't double quotes around the rel value.

I suspect PR #5 may fix it. (CC @AlaricWhitney)

**Comment by peterhellberg** [comment]
@dmitshur Thank you for opening an issue, I will try to take a look at this soon. The PR was unfortunately left unattended since I didn't have much bandwidth to work on open source projects last year.

**Comment by peterhellberg** [comment]
Today I finally pushed a minor change (tagged as `v1.1.1`) which no longer panics for the input `</example.png>;rel=preload;as=image`

Example: <https://go.dev/play/p/_Mavz4CI4Uw>

It does not, however, produce the desired result (since the returned value is an empty `link.Group`)

**Comment by peterhellberg** [comment]
With the release of `v1.2.0` we can parse `</example.png>;rel=preload;as=image` into a `link.Group` (encoded as JSON)
```json
{"preload":{"URI":"/example.png","Rel":"preload","Extra":{"as":"image"}}}
```

Example: https://go.dev/play/p/qQ3jRiXM1xq
